### ISSUE TITLE
Confusing instruction for Icecream shop

### ISSUE THREAD

**Issue by keithagroves** [League-central/java-modules#177]
I had a student start the recipe and they immediately were confused by the first "step". There are a few processing recipes like this. I think we should clarify by writing "//Goal: Draw an ice cream cone with many flavors and lots of sprinkles!" rather than "// Draw an ice cream cone with many flavors and lots of sprinkles!" 

https://github.com/League-central/java-modules/blob/9a0efaef1e7ca92a2b401b2dfeecc7a5a3df26d0/Level0-Module2/src/_02_methods/_5_ice_cream_shop/ice_cream_shop/ice_cream_shop.pde#L3

**Comment by jaLeague** [comment]
I always present the recipe web page (where the goal is described) before the student starts to code: ( https://central.jointheleague.org/levels/Level0/Recipes/IceCreamShop.html )
However, I can see how this might be confusing for students who skip that step.

**Comment by jaLeague** [comment]
Oops. I accidentally committed straight into the Development branch :(

**Comment by keithagroves** [comment]
That's fine. It's a very small fix. Can you also do the other processing recipes in this module?
