### ISSUE TITLE
We need to redirect the deprecated bit.ly links 

### ISSUE THREAD

**Issue by keithagroves** [League-central/java-modules#196]
**Describe the bug**
Quote from teacher:
`http://bit.ly/L0recipes however we then found there is another link http://level0.jointheleague.org/ that contains different recipes.  Which one should we use?
`

**Comment by anurup-joseph** [comment]
As a clarification, in my Koala (Level 0/1/2/3), we noticed that there is a parallel structure between URL's in the form
   http://bit.ly/LXrecipes
and those in form
   http://levelX.jointheleague.org/

@keithagroves informed me that the latter URL's are the correct ones, so I think that it would be best to remove the former pages and redirect the bit.ly URL's to the correct latter ones.  Thank you.

**Comment by jaLeague** [comment]
Because bit.ly links cannot be edited, this requires fixes to files in archived repositories.  They will have to be unarchived, changed, then re-archived.

**Comment by jaLeague** [comment]
Weirdly, the bit.ly link for level 3 recipes already went to central (students) index, whereas all the others were going to old archived repos (which have now been amended and re-archived).
All the bit.ly student menu links should now work as required.

**Comment by jaLeague** [comment]
I believe that all the bit.ly/lXrecipes links should now redirect to the levelX.jointheleague.org menus.
Thank you for finding and reporting this issue.

Best,
Jackie

**Comment by anurup-joseph** [comment]
Thank you for fixing, Jackie.  I notice that, in Safari, the League icon at the bottom of the page looks huge and that the individual Module pages are misformatted.  Do you see that also?

**Comment by jaLeague** [comment]
I am not able to reproduce that. Could you please send me a snapshot of a misformatted screen?

**Comment by anurup-joseph** [comment]
Hi Jackie.  I now see the Module pages properly formatted.  The problem may have been with my system.  I'll let you know if I encounter the issue.  Thanks again!
