### ISSUE TITLE
Level 2 Mod 0 and Level 3 Mod 0 are duplicates

### ISSUE THREAD

**Issue by chmilk1** [League-central/java-modules#61]
**Is your feature request related to a problem? Please describe.**
Both modules have the exact same content.
 
**Describe the solution you'd like**
One should be removed.

**Additional context**
Links to both Modules:
https://github.com/League-central/java-modules/tree/development/Level3-Module0/src/_00_IntroToArrays
https://github.com/League-central/java-modules/tree/development/Level2-Module0/src/arrays

**Comment by keithagroves** [comment]
Thanks!
